### ISSUE TITLE
请问一下，怎么取消数据库2h重置一次？

### ISSUE THREAD

**Issue by Mcoon** [lastwhispers/permission#12]
请问一下，怎么取消数据库2h重置一次？

**Comment by lastwhispers** [comment]
cn.lastwhisper.core.task.GoBackTask别把这个类注入到IOC容器即可

**Comment by Mcoon** [comment]
好的，谢谢大佬，正在拜读！！


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"LastWhispers"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月24日(星期五) 下午4:04
收件人:&nbsp;"lastwhispers/permission"<permission@noreply.github.com&gt;;
抄送:&nbsp;"co ."<1730717923@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [lastwhispers/permission] 请问一下，怎么取消数据库2h重置一次？ (#12)





 
cn.lastwhisper.core.task.GoBackTask别把这个类注入到IOC容器即可
